import assert from 'node:assert/strict';
import { handleLead, resetLeadLimitsForTest } from '../src/lib/lead-handler';
import { normalizeRuPhone } from '../src/lib/contact-validation';
process.env.ALLOW_LOCAL_PREVIEW = 'true';
let delivered = 0;
const delivery = async (mail: { html:string; replyTo:string }) => { delivered++; assert.equal(mail.replyTo,'oleg@example.com'); assert.ok(!mail.html.includes('<script>alert')); assert.ok(mail.html.includes('&lt;script&gt;')); };
const lead = { name:'Олег', email:'oleg@example.com', phone:'8 (999) 123-45-67', message:'Проверка <script>alert(1)</script>', consent:true };
const request = (body:unknown, origin='http://127.0.0.1:3100') => new Request('http://127.0.0.1:3100/api/sendMail',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)});
assert.equal(normalizeRuPhone(lead.phone),'79991234567');
assert.equal((await handleLead(request(lead,'https://evil.example'),delivery,'one')).status,403);
assert.equal((await handleLead(request({website:'bot'}),delivery,'one')).status,200);
assert.equal(delivered,0);
assert.equal((await handleLead(request({...lead,consent:false}),delivery,'two')).status,400);
assert.equal((await handleLead(request({...lead,phone:'123'}),delivery,'three')).status,400);
assert.equal((await handleLead(request({...lead,message:'x'.repeat(20_000)}),delivery,'large')).status,413);
assert.equal((await handleLead(request({...lead,technical:{power:'x'.repeat(40)}}),delivery,'technical')).status,400);
assert.equal((await handleLead(request(lead),delivery,'four')).status,200);
assert.equal(delivered,1);
assert.equal((await handleLead(request(lead),async()=>{throw Error('SMTP failure');},'failure')).status,502);
for (let i=0;i<5;i++) assert.equal((await handleLead(request({...lead,consent:false}),delivery,'rate')).status,400);
const limited = await handleLead(request(lead),delivery,'rate');
assert.equal(limited.status,429); assert.ok(limited.headers.get('Retry-After'));
assert.equal(delivered,1);
resetLeadLimitsForTest();
// The fallback bucket is shared by visitors when proxy IP trust is disabled.
for (let i=0;i<50;i++) assert.equal((await handleLead(request({...lead,consent:false}),delivery)).status,400);
const sharedLimited = await handleLead(request(lead),delivery);
assert.equal(sharedLimited.status,429);
assert.ok(sharedLimited.headers.get('Retry-After'));
assert.equal(delivered,1);
// A saturated fallback bucket must not consume a known client's allowance.
assert.equal((await handleLead(request({...lead,consent:false}),delivery,'separate-client')).status,400);
resetLeadLimitsForTest();
let reserved = 0;
let finished: 'sent' | 'failed' | undefined;
const store = { reserve: async () => { reserved++; return { id: 1, created: true }; }, finish: async (_id: number, status: 'sent' | 'failed') => { finished = status; } };
assert.equal((await handleLead(request({ ...lead, website: 'bot' }), delivery, 'stored-bot', store)).status, 200);
assert.equal((await handleLead(request({ ...lead, consent: false }), delivery, 'stored-invalid', store)).status, 400);
assert.equal(reserved, 0);
assert.equal((await handleLead(request(lead), async () => { throw Error('SMTP failure'); }, 'stored-failure', store)).status, 200);
assert.equal(finished, 'failed');
const priorDelivery = delivered;
assert.equal((await handleLead(request(lead), delivery, 'stored-db-failure', { ...store, reserve: async () => { throw Error('DB failure'); } })).status, 503);
assert.equal((await handleLead(request(lead), delivery, 'stored-duplicate', { ...store, reserve: async () => ({ id: 1, created: false }) })).status, 200);
assert.equal(delivered, priorDelivery);
console.log('Lead validation, normalization, consent, honeypot, origin, size limit, rate limit, escaping and SMTP failure checks passed. No real mail sent.');
